version: '3'
services:
  polybot:
    image: polybot:0.3.3
    container_name: polybot
    env_file:
      - .env
    ports:
      - "8443:8443"
    networks:
      - mongodb_mongoCluster
    tty: true
    stdin_open: true
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials

networks:
  mongodb_mongoCluster:
    external: true