version: '3'
services:
  bot-yolo5:
    image: yolo5:0.1.0
    container_name: bot-yolo5
    networks:
      - mongoCluster
    environment:
      - BUCKET_NAME=max-yolo5
    volumes:
      - ${HOME}/.aws/credentials:/root/.aws/credentials
    ports:
      - "8081:8081"
    links:
      - mongo1-1:mongodb

networks:
  mongoCluster:
    external: true